name: Build and Push Docker Image for network/benchmarks/netperf/nptest

on:
  release:
    types: [published, edited]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd network/benchmarks/netperf
        make push
      env:
        DOCKERREPO: ghcr.io/${{ github.repository_owner }}/nptest
        # IMAGE_TAG should be commit id if push else tag if release
        IMAGE_TAG: ${{ github.event.release.tag_name }}
